export const SEED = {
  events: [
    {
      id: "e1",
      name: "HackIndore 2024",
      type: "Hackathon",
      date: "2024-11-15",
      mode: "Offline",
      venue: "IET DAVV, Indore",
      capacity: 200,
      description: "24-hour hackathon for students across MP.",
      tracks: "Web, AI/ML, FinTech",
      prizes: "₹1,00,000 total prize pool",
      status: "past",
    },
    {
      id: "e2",
      name: "GDG DevFest Indore 2025",
      type: "Hackathon",
      date: "2025-02-20",
      mode: "Offline",
      venue: "Brilliant Convention Centre, Indore",
      capacity: 300,
      description: "Annual developer festival by GDG Indore.",
      tracks: "Cloud, Mobile, AI",
      prizes: "₹75,000 total prize pool",
      status: "upcoming",
    },
    {
      id: "e3",
      name: "Flutter Meetup Indore",
      type: "Meetup",
      date: "2025-01-18",
      mode: "Offline",
      venue: "91springboard, Indore",
      capacity: 80,
      description: "Monthly Flutter developer meetup.",
      tracks: "Flutter, Dart",
      prizes: "None",
      status: "upcoming",
    },
  ],
  registrations: [
    { id: "r1", eventId: "e1", name: "Aarav Sharma", email: "aarav@iitindore.ac.in", college: "IIT Indore", role: "Student", github: "aaravsharma", team: "ByteBuilders", status: "Checked-in", time: "2024-11-01T10:00:00Z" },
    { id: "r2", eventId: "e1", name: "Priya Patel", email: "priya@davv.ac.in", college: "DAVV Indore", role: "Student", github: "priyapatel", team: "CodeCraft", status: "Checked-in", time: "2024-11-01T10:05:00Z" },
    { id: "r3", eventId: "e1", name: "Rohan Verma", email: "rohan@sgsits.ac.in", college: "SGSITS Indore", role: "Student", github: "rohanverma", team: "ByteBuilders", status: "Checked-in", time: "2024-11-01T10:10:00Z" },
    { id: "r4", eventId: "e1", name: "Sneha Joshi", email: "sneha@medicaps.ac.in", college: "Medicaps University", role: "Student", github: "snehajoshi", team: "HackSters", status: "Checked-in", time: "2024-11-01T10:15:00Z" },
    { id: "r5", eventId: "e1", name: "Arjun Gupta", email: "arjun@ietdavv.edu.in", college: "IET DAVV", role: "Student", github: "arjungupta", team: "CodeCraft", status: "Checked-in", time: "2024-11-01T10:20:00Z" },
    { id: "r6", eventId: "e1", name: "Kavya Singh", email: "kavya@acropolis.in", college: "Acropolis Institute", role: "Student", github: "kavyasingh", team: "HackSters", status: "Approved", time: "2024-11-01T10:25:00Z" },
    { id: "r7", eventId: "e1", name: "Neel Mehta", email: "neel@gmail.com", college: "TechCorp", role: "Professional", github: "neelmehta", team: "TechNovators", status: "Approved", time: "2024-11-01T10:30:00Z" },
    { id: "r8", eventId: "e1", name: "Divya Tiwari", email: "divya@davv.ac.in", college: "DAVV Indore", role: "Student", github: "divyatiwari", team: "TechNovators", status: "Approved", time: "2024-11-01T10:35:00Z" },
    { id: "r9", eventId: "e2", name: "Rahul Choudhary", email: "rahul@iitindore.ac.in", college: "IIT Indore", role: "Student", github: "rahulc", team: "NeuralNinjas", status: "Registered", time: "2024-12-10T09:00:00Z" },
    { id: "r10", eventId: "e2", name: "Ananya Dubey", email: "ananya@sgsits.ac.in", college: "SGSITS Indore", role: "Student", github: "ananyadubey", team: "CloudChasers", status: "Registered", time: "2024-12-11T09:00:00Z" },
    { id: "r11", eventId: "e2", name: "Vikram Yadav", email: "vikram@medicaps.ac.in", college: "Medicaps University", role: "Student", github: "vikramy", team: "NeuralNinjas", status: "Approved", time: "2024-12-12T09:00:00Z" },
    { id: "r12", eventId: "e2", name: "Pooja Malviya", email: "pooja@acropolis.in", college: "Acropolis Institute", role: "Student", github: "poojamalviya", team: "CloudChasers", status: "Registered", time: "2024-12-13T09:00:00Z" },
    { id: "r13", eventId: "e3", name: "Siddharth Puri", email: "sid@gmail.com", college: "TechStartup", role: "Professional", github: "sidpuri", team: "", status: "Registered", time: "2024-12-15T09:00:00Z" },
    { id: "r14", eventId: "e3", name: "Meera Kulkarni", email: "meera@davv.ac.in", college: "DAVV Indore", role: "Student", github: "meerak", team: "", status: "Approved", time: "2024-12-16T09:00:00Z" },
    { id: "r15", eventId: "e3", name: "Harsh Agrawal", email: "harsh@sgsits.ac.in", college: "SGSITS Indore", role: "Student", github: "harshagrawal", team: "", status: "Registered", time: "2024-12-17T09:00:00Z" },
  ],
  teams: [
    { id: "t1", eventId: "e1", name: "ByteBuilders", members: ["Aarav Sharma", "Rohan Verma"], projectName: "FarmConnect", description: "AI-powered crop advisory for small farmers", github: "https://github.com/bytebuilders/farmconnect", demo: "https://farmconnect.vercel.app" },
    { id: "t2", eventId: "e1", name: "CodeCraft", members: ["Priya Patel", "Arjun Gupta"], projectName: "EduTrack", description: "Student attendance and progress tracking using facial recognition", github: "https://github.com/codecraft/edutrack", demo: "https://edutrack.netlify.app" },
    { id: "t3", eventId: "e1", name: "HackSters", members: ["Sneha Joshi", "Kavya Singh"], projectName: "SafeRide", description: "Ride sharing app with SOS features for women safety", github: "https://github.com/hacksters/saferide", demo: "https://saferide.vercel.app" },
    { id: "t4", eventId: "e1", name: "TechNovators", members: ["Neel Mehta", "Divya Tiwari"], projectName: "WasteWise", description: "Smart waste management system with IoT sensors", github: "https://github.com/technovators/wastewise", demo: "https://wastewise.vercel.app" },
    { id: "t5", eventId: "e2", name: "NeuralNinjas", members: ["Rahul Choudhary", "Vikram Yadav"], projectName: "MedBot", description: "AI health assistant for rural clinics", github: "", demo: "" },
    { id: "t6", eventId: "e2", name: "CloudChasers", members: ["Ananya Dubey", "Pooja Malviya"], projectName: "LocalMart", description: "Hyperlocal e-commerce for kirana stores", github: "", demo: "" },
  ],
  scores: [
    { teamId: "t1", innovation: 9, technical: 8, design: 8, impact: 9 },
    { teamId: "t2", innovation: 7, technical: 9, design: 7, impact: 8 },
    { teamId: "t3", innovation: 8, technical: 7, design: 9, impact: 9 },
    { teamId: "t4", innovation: 8, technical: 8, design: 7, impact: 8 },
  ],
  activityLog: [
    { id: "a1", activity: "event.created", label: "Event Created", detail: "HackIndore 2024", time: "2024-10-01T09:00:00Z" },
    { id: "a2", activity: "registration.created", label: "New Registration", detail: "Aarav Sharma → HackIndore 2024", time: "2024-11-01T10:00:00Z" },
    { id: "a3", activity: "registration.created", label: "New Registration", detail: "Priya Patel → HackIndore 2024", time: "2024-11-01T10:05:00Z" },
    { id: "a4", activity: "registration.approved", label: "Registration Approved", detail: "Kavya Singh → HackIndore 2024", time: "2024-11-02T11:00:00Z" },
    { id: "a5", activity: "submission.received", label: "Submission Received", detail: "FarmConnect by ByteBuilders", time: "2024-11-15T20:00:00Z" },
    { id: "a6", activity: "submission.received", label: "Submission Received", detail: "EduTrack by CodeCraft", time: "2024-11-15T20:30:00Z" },
    { id: "a7", activity: "results.published", label: "Results Published", detail: "HackIndore 2024 — Winner: SafeRide", time: "2024-11-16T12:00:00Z" },
    { id: "a8", activity: "event.created", label: "Event Created", detail: "GDG DevFest Indore 2025", time: "2024-12-01T09:00:00Z" },
    { id: "a9", activity: "registration.created", label: "New Registration", detail: "Rahul Choudhary → GDG DevFest Indore 2025", time: "2024-12-10T09:00:00Z" },
    { id: "a10", activity: "participant.checked_in", label: "Participant Checked In", detail: "Aarav Sharma → HackIndore 2024", time: "2024-11-15T08:00:00Z" },
  ],
};
